version: '3.1'

# Run local database
services:
  db:
    container_name: multi_tenant_db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: hello123
      POSTGRES_DB: master
    ports:
      - "5435:5432"
    volumes:
      - ./docker/postgresql/volumes:/var/lib/postgresql